version: "3"
services:
  api:
    image: express-app
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app

  web:
    image: express-app
    networks:
      - backend
    command: sh

networks:
  backend:
